SELECT PE.DH_REFNO,PE.DH_BCODE,PE.DH_BBRCODE,PE.DH_NAME,PE.DH_AGECODE,PE.DH_AGENAME,PE.DH_NIC,PE.DH_BR,PE.DH_PADD1,PE.DH_PADD2,PE.DH_PADD3,PE.DH_PADD4,
  PE.DH_PHONE,PE.DH_EMAIL,PE.DH_IADD1,PE.DH_IADD2,PE.DH_IADD3,PE.DH_IADD4,PE.DH_PFROM,PE.DH_PTO,PE.DH_UCONSTR,PE.DH_OCCU_CAR,
  PE.DH_OCC_YES_REAS,PE.DH_HAZ_OCCU,PE.DH_HAZ_YES_REA,PE.DH_VALU_BUILD,PE.DH_VALU_WALL,PE.DH_VALU_TOTAL,PE.DH_AFF_FLOOD,PE.DH_AFF_YES_REAS,PE.DH_WBRICK,PE.DH_WCEMENT,PE.DH_DWOODEN,PE.DH_DMETAL,PE.DH_FTILE,
  PE.DH_FCEMENT,PE.DH_RTILE,PE.DH_RASBES ,PE.DH_RGI,PE.DH_RCONCREAT,PE.DH_COV_FIRE,PE.DH_COV_LIGHT,PE.DH_COV_FLOOD,
  PE.DH_CFWATERAVL,PE.DH_CFYESR1,PE.DH_CFYESR2,PE.DH_CFYESR3,PE.DH_CFYESR4,PE.DH_ENTERED_BY,PE.DH_ENTERED_ON,PE.DH_HOLD,
------------------------------>>>>>>>>>>>>>>>>>>>
  SC.SC_REF_NO,SC.SC_POLICY_NO,SC.SC_SUM_INSU,SC.SC_NET_PRE,SC.SC_RCC,
  SC.SC_TR,SC.SC_ADMIN_FEE,SC.SC_POLICY_FEE,SC.SC_NBT,SC.SC_VAT,SC.SC_TOTAL_PAY,SC.CREATED_ON,SC.CREATED_BY,SC.FLAG    
        FROM 
  
        QUOTATION.FIRE_DH_PROPOSAL_ENTRY PE
        INNER JOIN QUOTATION.FIRE_DH_SCHEDULE_CALC SC
        ON PE.DH_REFNO= SC.SC_REF_NO
        WHERE PE.DH_REFNO IS NOT NULL
        AND PE.DH_REFNO=''       
        AND SC.SC_POLICY_NO=''
        
        AND PE.DH_HOLD=''
        
SQL += "AND(TO_DATE(TO_CHAR(PE.DH_ENTERED_ON,'DD/MM/YYYY'),'DD/MM/YYYY') >= TO_DATE('" + START_DATE + "','DD/MM/YYYY') ";
SQL += "AND TO_DATE(TO_CHAR(PE.DH_ENTERED_ON,'DD/MM/YYYY'),'DD/MM/YYYY') <= TO_DATE('" + END_DATE + "','DD/MM/YYYY')) ";   
        
select * from QUOTATION.FIRE_DH_PROPOSAL_ENTRY PE
